services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root2021
      - MYSQL_USER=institute
      - MYSQL_PASSWORD=institute
      - MYSQL_DATABASE=institute
