name: Build and deploy
on:
  pull_request:
    branches: [javaconfig]

jobs:
  deploy:
    name: Deploy on Jetty
    runs-on: ubuntu-latest
    services:
      jetty:
        image: jetty:9.4.43-jre11
        ports:
          - 8282:8080
        env:
          SPRING_PROFILES_ACTIVE: jdbc
        volumes:
          - /host/webapps:/var/lib/jetty/webapps

      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root2021
          MYSQL_DATABASE: institute
          MYSQL_USER: institute
          MYSQL_PASSWORD: institute

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt'
          java-version: '11'
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build project
        run: mvn -B package -P JDBC_MySQL

      - name: Copy to webapps folder
        run: |
          sudo cp -f /home/runner/work/Students-WebApp/Students-WebApp/target/Students-WebApp.war /host/webapps
          if [ -f /host/webapps/Students-WebApp.war ]
          then
            echo "File copied to /host/webapps"
          else
            echo "File not copied to /host/webapps"
            exit 1
          fi
          echo "Timeout for 10 sec (app must deploy on Jetty during this time)"
          sleep 10

      - name: Webapp deploy test
        run: |
          HTTP_CODE=$(curl http://localhost:8282/Students-WebApp/students -s -o /dev/null -I -w "%{http_code}")
          if [[ $HTTP_CODE -eq 200 ]]
          then
            echo "Success. http_code: $HTTP_CODE"
          else
            echo "Fail. http_code: $HTTP_CODE"
            exit 1
          fi
