name: Lint Code Base

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - master

jobs:

  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Java through maven
        run: mvn -B checkstyle:check --file pom.xml

      - name: Lint remaining through Mega-Linter
        uses: nvuillam/mega-linter@v4
        env:
          ENABLE: SQL,CSS,XML,YAML,MARKDOWN
          DISABLE: COPYPASTE,SPELL
          #TODO VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}